---
title: "Simulate Time Series"
runtime: shiny
output: html_document
---

This is an interactive document.  It interactively simmulates a Moving average order 2 model.
The same code that could simulate the series non interactively is also included.

Make sure you have the following packages installed on your system.
```{r,echo=FALSE,message=FALSE}
# load packages ####
# if you do not have these packages - install.packages('package name')
library(tidyquant)
library(forecast)
library(quantmod)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(xts)
library(shiny)
```

```{r,echo=FALSE}
inputPanel(
  sliderInput("phi_1","Correlation in First MA component: ",min=0, max=0.99999,value=0.5,step = 0.01),
  sliderInput("phi_2","Correlation in Second MA component: ",min=0, max=0.99999,value=0.5,step = 0.01)
)
``` 

```{r,echo=FALSE}
x <- reactive({ 
  date <- seq.Date(as.Date("2001/01/01"),as.Date("2013/01/01"),"days") 
  l <- length(date) 
  y <-arima.sim(model=list(ma=c(input$phi_1,input$phi_2)),n=l) 
  d <- data.frame(date=date,y=y) 
  x <- xts(d[,-1],order.by = d[,1]) 
})
```

```{r,echo=FALSE,message=FALSE}
renderPlot({
  plot(x())
})
``` 
```{r,echo=FALSE}
renderPlot({
acf(x())
})
```
```{r,echo=FALSE}
renderPlot({
pacf(x())
})
```

```{r}
renderPrint({
fit_2 <- auto.arima(x())
broom::tidy(fit_2) 
})

```


```{r}
renderPrint({
  arima(x(),order = c(0,0,2)) 
})
```

```{r,echo=FALSE,include=FALSE,eval=FALSE}
  date <- seq.Date(as.Date("2001/01/01"),as.Date("2013/01/01"),"days") 
  l <- length(date) 
  y <-arima.sim(model=list(ma=c(0.9)),n=l) 
  x <- data.frame(date=date,y=y) 
  x <- xts(x[,-1],order.by = x[,1]) 
```

```{r,echo=FALSE,message=FALSE,include=FALSE,eval=FALSE}
  plot(x)
``` 

```{r,echo=FALSE,include=FALSE,eval=FALSE}
print(acf(x))
print(pacf(x) )
print(arima(x,order=c(0,0,1)))
```

