---
title: "Replicate analysis by Ani Katchova"
output: html_notebook
---

Load required packages
```{r}
library(quadprog)
library(tseries)
library(lubridate)
library(tidyverse)
```

# Time Series ARIMA Models in R
Copyright 2013 by Ani Katchova
## Read in the timeseries_ppi data
```{r}
getwd()
infile <- file.path(getwd(),"data","timeseries_ppi.csv")
mydata<- read_csv(infile)
names(mydata)
sapply(mydata,"class")
```
##Define the variables 
* t: convert yearqrt to a time variable
* d.Y: First difference
```{r}
d <- mydata %>%
  mutate(t = yq(yearqrt)) %>%
  mutate(Y = ppi) %>%
  mutate(d.Y = Y - lag(Y) ) %>%
  mutate(dppi =  ) %>%
  mutate(lppi = lag(ppi))  %>%
  mutate(ldppi=lag(dppi))
# Create a version without missing differences
length(d$d.Y)
d1<-d[!is.na(d$d.Y),]
length(d1$d.Y)
names(d)
head(d[,c("t","ppi","dppi","lppi","ldppi","Y","d.Y")])
```
```{r}
ylist <- enquote(c('ppi'))
dylist <- enquote(c('dppi'))
time <- enquote(c('t'))
lylist <- enquote(c('lppi'))
trend<- enquote(c('trend'))
xlist<-enquote(c('cpi','gdp'))
```
```{r}
install.packages('Hmisc')
install.packages('ggfortify')
install.packages('forecast')
library(glue)
library(Hmisc)
library(ggfortify)
library(forecast)
```


## Descriptive statistics plots
```{r}
d %>% select(!!ylist,!!dylist,!!time) %>% describe()
```

## Plots
```{r}
d %>% ggplot(aes(t,Y)) + geom_line() + ggtitle("Y by Time")

```
```{r}
d %>% ggplot(aes(t,d.Y)) + geom_line() + ggtitle("Dif of Y by Time")
```

Look at Dickey Fuller


Dickey-Fuller test for original variable
```{r}
with(d,adf.test(Y, alternative="stationary", k=0))
with(d,adf.test(Y, alternative="stationary", k=1))
with(d,adf.test(Y, alternative="stationary", k=2))
```
```{r}
with(d,adf.test(Y, alternative="explosive", k=0))
```

Summary statistics
```{r}
with(d,summary(lm(dppi ~ lppi, na.action=na.omit)))
```



Dickey-Fuller for differenced variable
```{r}
with(d1,adf.test(d.Y, alternative="stationary", k=0))
with(d1,adf.test(d.Y, alternative="stationary", k=1))
with(d1,adf.test(d.Y, alternative="stationary", k=2))

```




```{r}
# ACF and PACF
with(d,acf(Y))
with(d,pacf(Y))
with(d1,acf(d.Y[!is.na(d.Y)]))
with(d1,pacf(d.Y[!is.na(d.Y)]))
```
```{r}
autoplot(lm(dppi ~ lppi + trend, na.action=na.omit,data=d))
str(dppi.lm)
dppi.res <- resid(dppi.lm)
str(dppi.res)
```
https://cran.r-project.org/web/packages/ggfortify/vignettes/plot_ts.html
```{r}
# ARIMA(1,0,0) or AR(1)
names(d)
mts<-ts(d[,c('Y','ppi','dppi','t','lppi','cpi','gdp')],frequency=1)
autoplot(mts)
library(forecast)
d.arima <-auto.arima(d$Y)
d.forecast <- forecast(d.arima,level=c(95),h=50)
autoplot(d.forcast)
d.arima_2<-arima(d$Y,order=c(1,1,0))
d.forcast_2 <- forecast(d.arima_2,level=c(95),h=50)
autoplot((d.forcast_2))
```

```{r}
# ARIMA(2,0,0) or AR(2)
with(d,arima(Y, order = c(2,0,0)))
```


```{r}
# ARIMA(0,0,1) or MA(1)
with(d,arima(Y, order = c(0,0,1)))
```
```{r}
# ARIMA(1,0,1) or AR(1) MA(1)
with(d,arima(Y, order = c(1,0,1)))
```


```{r}
# ARIMA on differenced variable
# ARIMA(1,1,0)
with(d1,arima(d.Y, order = c(1,0,0)))
with(d1,arima(Y, order = c(1,1,0)))
```

```{r}
# ARIMA(0,1,1)
with(d1,arima(d.Y, order = c(0,0,1)))
```

```{r}
# ARIMA(1,1,1)
with(d1,arima(d.Y, order = c(1,0,1)))
```

```{r}
# ARIMA(1,1,3)
with(d1,arima(d.Y, order = c(1,0,3)))
```

```{r}
# ARIMA(2,1,3)
with(d1,arima(d.Y, order = c(2,0,3)))
```

```{r}
# ARIMA(1,0,1) forecasting
mydata.arima101 <- with(d1,arima(Y, order = c(1,0,1)))
mydata.pred1 <- predict(mydata.arima101, n.ahead=100)
plot (Y)
lines(mydata.pred1$pred, col="blue")
lines(mydata.pred1$pred+2*mydata.pred1$se, col="red")
lines(mydata.pred1$pred-2*mydata.pred1$se, col="red")
```

```{r}
# ARIMA(1,1,1) forecasting
mydata.arima111 <- with(d1,arima(d.Y, order = c(1,0,1)))
mydata.pred1 <- predict(mydata.arima111, n.ahead=100)
plot (d.Y)
lines(mydata.pred1$pred, col="blue")
lines(mydata.pred1$pred+2*mydata.pred1$se, col="red")
lines(mydata.pred1$pred-2*mydata.pred1$se, col="red")
```



