---
title: "R Notebook"
output: html_notebook
---

Make sure the proper libraries are loaded
```{r}
library(data.table)
library(quadprog)
library(tseries)
library(lubridate)
library(tidyverse)
library(ggplot2)
library(readxl)
library(gk)
library(shiny)
library(miniUI)
library(shiny)
library(miniUI)
library(ggplot2)

```

This is a gadget to explore the gk distriburtion.  Run this part to load the function, then run it in the next chunk
```{r}
plot_gk <- function() {
  ui <- miniPage(
    miniContentPanel(
    # Application title
   titlePanel("g&k distribution"),
   
   # Sidebar with a slider input for number of bins 
   sidebarLayout(
      sidebarPanel(
        actionButton(inputId = "go", label = "Calculate Results"), 
        sliderInput("A",
                     "A:",
                     min = 1,
                     max = 5,
                     step = 0.1,
                     value = 3), 
        sliderInput("B",
                     "B:",
                     min=0,max=5,step=0.1,value=1), 
        sliderInput("kh",
                     "k:",
                     min=-1,max=1,step=0.01,value=0.5), 
        sliderInput("g",
                     "g:",
                     min=-2,max=2,step=0.01,value=0), 
        selectInput("dist","gk or gh",choices = list("gk" = "rgk",'gh' = 'rgh'),selected = 'rgk') 
        ),
      
      # Show a plot of the generated distribution
      mainPanel(
        plotOutput("regPlot"), 
        verbatimTextOutput("stats") ,
        plotOutput("logPlot"), 
        verbatimTextOutput("statslog")  
        ) 
   )  
   )  
  ) 

server <- function(input, output, session) {
  # Modify the slider depending on what distribution the user wants to model
  observeEvent(input$dist,{
   if (input$dist == 'rgk') {
     updateSliderInput(session,
                       "kh", 
                       "k:", 
                       min=-1,max=1,step=0.01) 
   } 
    else {
      updateSliderInput(session,
                       "kh", 
                       "h:", 
                       min=-1,max=1,step=0.01)  
      } 
  },priority = 1)
  
 my_data<-eventReactive({input$go; input$A},{
   # When the "go" button is pushed or the A input changes, then update the data
   if (input$dist == 'rgk') { 
     tibble(x = do.call(input$dist,list(5000,A=input$A,B=input$B,g=input$g,k=input$kh)) )
   }
   else {
     tibble(x = do.call(input$dist,list(5000,A=input$A,B=input$B,g=input$g,h=input$kh)) )
   } 
    
  })  
 my_log_data <- reactive({
   #if my_data() changes, update the log version of the data.
   my_data() %>% filter(x > 0)
 })
 
 # create the outputs.
 output$logPlot <- renderPlot({ 
   # generate bins based on input$bins from ui.R 
   my_log_data() %>% ggplot() + aes(x=x) + scale_x_log10() + geom_density() + ggtitle("Log Plot") 
   }) 
 output$regPlot <- renderPlot({ 
   # generate bins based on input$bins from ui.R 
   my_data() %>% ggplot() + aes(x=x) + geom_density() 
   })
 output$statslog <- renderPrint({
   summary(log(my_log_data())) 
   })
 output$stats <- renderPrint({
   summary(my_data())
 })
} 
   
    
# Run the application 
runGadget(ui , server, viewer = browserViewer())
}
```
Run the gk plot gadget.  Note that you have to select the "Calculate" button to refresh the graph after making changes.
```{r}
plot_gk()
```

