---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(gk)
library(readxl)
```


# Read in the Excel Data.
* Assume the data is in a subdirectory called timeseries/data
* Assume the name of the data xlsx data set is Data to Test g&h.xlsx
* The column with the data should be called "Data"
```{r,echo=FALSE}
my_dir  <- file.path('~','Documents','timeseries','data' )
my_dir  <- file.path('.','data' )
my_file <- file.path(my_dir,'datatotestgh.xlsx')
d <- read_excel(my_file)
names(d)
```

# Plot a density estimate of the data
```{r}
d %>% 
  ggplot() + aes(x=Data) + scale_x_log10() + geom_density() + ggtitle("Financial Time Series \n Log scale") +
  theme(axis.text.x = element_text( ))
```
```{r}
library(e1071)
```

```{r}
initial_parameters <- function(d,last='h') {
  A <- d %>% summarise(median(Data))
  B <- d %>% summarise(sd(Data))
  return(c('A'=as.numeric(A),'B' = as.numeric(B),'g'= 0, 'h' = 50))
}
min_parameters <- function(d,last='h') {
  A <- d %>% summarize(quantile(Data,c(.25)))
  B <- d %>% summarise( 0.5 * sd(Data))
  return(c('A'=as.numeric(A),'B' = as.numeric(B),'g'= -50, 'h' = 0))
}
max_parameters <- function(d,last='h') {
  A <- d %>% summarize(quantile(Data,c(.75)))
  B <- d %>% summarise(2 * sd(Data))
  return(c('A'=as.numeric(A),'B' = as.numeric(B),'g'= 50, 'h' = 100)) 
}

```

```{r}

initial_parameters(d)
```


```{r}
# Estimate the parameters
N <- 500
theta_max <- max_parameters(d)
theta_min <- min_parameters(d)
theta     <- initial_parameters(d)
out = fdsa(x, N=N, model=c("gh"),theta0=theta, theta_min=theta_min, theta_max=theta_max,silent=FALSE)
```
```{r}
n <- length(out[,1])
out[n ,]
theta1 <- out[n ,]
names(theta1)
str(theta1)
theta1['A']
theta1['B']
```
```{r}
my_rgh <-rgh(length(d$Data),theta1['A'],theta1['B'],theta1['g'],theta1['h'])
```
```{r}
d$simulated <- my_rgh
```
```{r}
d_stacked <- d %>% select("Data","simulated") %>% gather() 
names(d_stacked)
```

```{r}
d_stacked %>% 
  ggplot() + aes(x=value,color=key) + geom_density() + 
  ggtitle("Financial Time Series \n Log scale") +
  theme(axis.text.x = element_text( ))
  
```



```{r}
#Look at the parameters check the results
theta_post<-out[length(out[,1]),]
theta_post
out[length(out[,1]),]
A <- theta_post['A']
B <- theta_post['B']
g <- theta_post['g']
h <- theta_post['h'] 
c(A,B,g,h)
probs <- c(0.001,0.005,0.01,0.05,0.01,0.5,0.99,0.995,0.999)
probs
qgh(probs,A=A,B=A,g=g,h=h)
quantile(x,probs)

#qgh(c(0.01,0.05,0.01,0.99,0.995,0.999),A=7890,B=47773,g=5,h=25)
```
```{r}
A <- theta_post['A']
B <- theta_post['B']
g <- theta_post['g'] + 30
h <- theta_post['h'] - 0
c(A,B,g,h)
qgh(probs,A=A,B=A,g=g,h=h)
quantile(x,probs)
```
```{r}
xs <- rgh(1381,A=A,B=A,g=g,h=h)
```




```{r}
N
c(mean(x),sd(x))
rm(out)
theta_min
theta_max
# The model parameters are A,B,g,h or k;
out = fdsa(x, N=N, model=c("gh"),theta0=theta1, theta_min=theta_min, theta_max=theta_max,silent=FALSE)
1:5
length(out[,1])



out = fdsa(x, N=N, model=c("gh"),theta0=c(mean(x),sd(x),0,0), theta_min=theta_min, theta_max=theta_max,silent=FALSE)
out
my_fdsa <-fdsa(d$Data, N=N, theta0=c(mean(d$Data),sd(d$Data),0,0),theta_min = c(-10,1E-5,-20,0),theta_max = c(20,30,10,20))

fdsa(d$Data, N=N, theta0=c(-100,-100,0,10),theta_min = c(-10,1E-5,-20,0),theta_max = c(200000,300000,10000,20))
isValid(c(1,2,3,4),2,c=0.8,model=c('gh'), initial_z = seq(-1,1,0.2))
```
```{r}
x = rgk(10, A=3, B=1, g=2, k=0.5) ##An unusually small dataset for fast execution of this example
out = fdsa(x, N=100, theta0=c(mean(x),sd(x),0,0), theta_min=c(-5,1E-5,-5,0), theta_max=c(5,5,5,5))
```



