---
title: "Time Series Analysis"
author: "Harlan A Nelson"
output:
  html_document:
    df_print: paged
---

This notebook compiles information from a variety of web sources regarding time series analysis.
This code is from the tidyquant tutorial.


There are a few packages related to time series analysis.  
* zoo
* xts
* quantmod
* TTR
* PerformanceAnalytics
* tidyquant

This notebook starts with tidyquant
```{r}
library(tidyquant)
```

```{r}
tq_transmute_fun_options()
```
```{r}
data("FANG")
```

```{r}
FANG
```
```{r}
FANG_annual_returns <- FANG %>% 
  group_by(symbol) %>% 
  tq_transmute(select = adjusted,
               mutate_fun = periodReturn,
               period = "yearly",
               type = "arithmetic")
FANG_annual_returns
```

```{r}
FANG_annual_returns %>% 
  ggplot(aes(x = date, y = yearly.returns, fill = symbol)) +
  geom_bar(stat = "identity") +
  geom_hline(yintercept = 0, color = palette_light()[[1]]) +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "FANG: Annual Returns",
       subtitle = "Get annual returns quickly with tq_transmute!",
       y = "Annual Returns", x = "") +
  facet_wrap(~ symbol, ncol = 2) +
  theme_tq()  +
  scale_fill_tq()
```


```{r}
FANG_daily_log_returns <- FANG %>% 
  group_by(symbol) %>% 
  tq_transmute(select = adjusted,
               mutate_fun = periodReturn,
               period = "daily",
               type = "log",
               col_rename = "monthly.returns")
```
```{r}
FANG_daily_log_returns %>% 
  ggplot() +
  aes(x = monthly.returns, fill = symbol) +
  geom_density(alpha = 0.5) +
  labs(title = "FANG: Charting the Daily Log Returns",
       x = "Monthly Returns",
       y = "Density") +
  theme_tq() +
  scale_fill_tq() +
  facet_wrap(~ symbol, ncol = 2)
```


```{r}
FANG %>% 
  group_by(symbol) %>% 
  tq_transmute(select = open:volume,
               mutate_fun = to.period,
               period = "months")
```
```{r}
FANG_daily <- FANG %>% 
  group_by(symbol)

FANG_daily %>% 
  ggplot() +
  aes(x = date, y = adjusted, color = symbol) +
  geom_line(size = 1) +
  labs(title = "Daily Stock Prices",
       x     = "", 
       y     = "Adjusted Proces", 
       color = "") +
  facet_wrap( ~ symbol, ncol = 2, scales = "free_y") +
  scale_y_continuous(labels = scales::dollar) +
  theme_tq() + 
  scale_color_tq()
```
```{r}
FANG_monthly <- FANG %>% 
  group_by(symbol) %>% 
  tq_transmute(select = adjusted,
               mutate_fun = to.period,
               period = "months")

FANG_monthly %>% 
  ggplot() +
  aes(x = date, y = adjusted, color = symbol) +
  geom_line(size = 1) +
  labs(title = "Monthly Stock Prices",
       x = "", y = "Adjusted Prices", color = "") +
  facet_wrap(~ symbol, ncol = 2, scales = "free_y") +
  scale_y_continuous(labels = scales::dollar) + 
  theme_tq() + 
  scale_color_tq()

```


```{r}
FANG_returns_monthly <- FANG %>% 
  group_by(symbol) %>% 
  tq_transmute(select     = adjusted,
               mutate_fun = periodReturn,
               period     = "monthly")
```
```{r}
baseline_returns_monthly <- "XLK"  %>% 
  tq_get(get   = "stock.prices",
         from  = "2013-01-01",
         to    = "2016-12-31") %>% 
  tq_transmute(select = adjusted,
               mutate_fun = periodReturn,
               period = "monthly")  
```

```{r}
returns_joined <- left_join(FANG_returns_monthly,
                            baseline_returns_monthly,
                            by = "date")
returns_joined
```


```{r}
FANG_rolling_corr <- returns_joined %>% 
  tq_transmute_xy(x = monthly.returns.x,
                  y = monthly.returns.y,
                  mutate_fun = runCor,
                  n = 6,
                  col_rename = "rolling.corr.6")
```

```{r}
FANG_rolling_corr %>% 
  ggplot() +
  aes(x = date, y = rolling.corr.6, color = symbol) +
  geom_hline(yintercept = 0, color = palette_light()[1]) +
  geom_line(size = 1) +
  labs(title = "FANG: Six Month Rolling Correlations to XLK",
       x = "", y = "Correlation", color = "") +
  facet_wrap(~ symbol, ncol = 2) +
  theme_tq() +
  scale_color_tq()
```
```{r}
names(returns_joined )
FANG_rolling_corr <- returns_joined %>% 
  tq_transmute_xy(x=monthly.returns.x,y=monthly.returns.y,
                  mutate_fun = runCor,
                  n = 6,
                  col_rename = "rolling.corr.6")
```

```{r}
FANG_rolling_corr %>% 
  ggplot() +
  aes(x = date, y = rolling.corr.6, color = symbol) +
  geom_hline(yintercept = 0, color = palette_light()[1]) +
  geom_line(size = 1) +
  labs(title = "FANG: Six Month Rolling Correlations to XLK",
       x = "", y = "Correlation", color = "") +
  facet_wrap(~ symbol, ncol = 2) +
  theme_tq() +
  scale_color_tq()
```
